tasks:
  goBuild:
    name: Build project
    command: cd gitpod-network-check && go build ./...
    triggeredBy:
      - manual
      - postEnvironmentStart

  goTest:
    name: Run tests
    command: cd gitpod-network-check && go test -v ./...
    triggeredBy:
      - manual
      - postEnvironmentStart